# Generated by Django 4.2.13 on 2024-10-10 22:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=50, verbose_name='Card number')),
                ('expiration_date', models.DateField(verbose_name='Expiration date')),
            ],
        ),
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True, verbose_name='Account number')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=17, verbose_name='Balance')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=17, verbose_name='Credit Limit')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Transaction ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=17, verbose_name='Amount')),
                ('transaction_date', models.DateField(verbose_name='Transaction date')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bank.card', verbose_name='Card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='credit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bank.creditaccount', verbose_name='Credit account'),
        ),
    ]
