# Generated by Django 4.2.13 on 2024-10-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Card number'),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='account_number',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Account number'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(db_index=True, verbose_name='Transaction date'),
        ),
    ]
