version: "3.7"

networks:
  qubilo_test_network:
    name: qubilo_test_network

volumes:
  qubilo_db_data:
    name: qubilo_db_data

services:

  db:
    image: postgres:14
    container_name: qubilo_test_db
    command: postgres -c 'max_connections=500'
    env_file:
      - ./.envs/db.env
    volumes:
      - qubilo_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - qubilo_test_network
    restart: always

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: qubilo_test/app:latest
    container_name: qubilo_test_app
    env_file:
      - ./.envs/db.env
      - ./.envs/app.env
    volumes:
      - ./app:/var/app
    ports:
      - 8000:8000
    networks:
      - qubilo_test_network
    depends_on:
      - db
    command: ["/start.sh"]
    deploy:
        resources:
            limits:
              cpus: 1
              memory: 2GB